import '@/app/globals.css';
import initTranslations from '@/app/i18n';
import i18nConfig from '@/app/i18n-config';
import TranslationProvider from '@/components/translations-provider';
import GlobalLayout from '@/layout/global-layout';
import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const i18nNamespaces = ['common'];

const RootLayout = async ({ children, params: { locale } }: Props) => {
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <TranslationProvider
          locale={locale}
          namespaces={i18nNamespaces}
          resources={resources}
        >
          <GlobalLayout>{children}</GlobalLayout>
        </TranslationProvider>
      </body>
    </html>
  );
};

export default RootLayout;
